---
- name: checkout dotfiles repo
  git: repo=git@github.com:jparkrr/dotfiles.git
       version=master
       dest=/Users/aryrabelo/dotfiles

- name: symlink dotfiles
  file: src=/Users/aryrabelo/dotfiles/{{ item }}
        dest=/Users/aryrabelo/{{ item }}
        state=link owner=aryrabelo force=true
  with_items:
    - .bash_profile
    - .bashrc
    - .inputrc
